name: beacon_example
version: 0.0.1
description: An absolute bare-bones web app.
author: kyorohiro <kyorohiro@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  umiuni2d_beacon:
    path: ../

transformers:
- dart_to_js_script_rewriter
